-- Create the dental_appointments table
create table dental_appointments (
  id bigint generated by default as identity primary key,
  patient_name text,
  email text,
  phone text,
  appointment_date text,
  treatment_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table dental_appointments enable row level security;

-- Create a policy to allow inserting data
create policy "Enable insert for all users" 
on dental_appointments for insert 
with check (true);

-- Create a policy to allow selecting data (optional)
create policy "Enable select for all users" 
on dental_appointments for select 
using (true);